DELIMITER //
DROP TABLE IF EXISTS PHONE CASCADE;
DROP TABLE IF EXISTS USER CASCADE;

/*CREACIÓN DE TABLAS*/
CREATE TABLE USER(
                     USERUUID VARCHAR(36),
                     USERNICK VARCHAR(100) NOT NULL,
                     USERPASS VARCHAR(255) NOT NULL,
                     USERDNI VARCHAR(9) NOT NULL,
                     USEREMAIL VARCHAR(255) NOT NULL,
                     USERBIRTHDATE DATE,
                     USERNAME VARCHAR(100) NOT NULL,
                     USERSURNAME VARCHAR(255) NOT NULL,
                     USERADDRESS VARCHAR(255),
                     USERMARK DECIMAL(5,2),
                     USERCARD VARCHAR(16),
                     USERDATA JSON,
                     USERTYPE ENUM('ADMIN', 'USER', 'SUPERUSER', 'GUEST', 'GOD') NOT NULL
);
//

CREATE TABLE PHONE(
                      PHONEID BIGINT AUTO_INCREMENT PRIMARY KEY,
                      PHONEPREFIX VARCHAR(5),
                      PHONENUMBER VARCHAR(9),
                      USERUUID VARCHAR(36)
);
//

/*CREACIÓN DE CLAVES PRIMARIAS*/
ALTER TABLE USER ADD CONSTRAINT PK_USER PRIMARY KEY (USERUUID);
ALTER TABLE USER ADD CONSTRAINT UK_USER UNIQUE (USERDNI);
ALTER TABLE USER ADD CONSTRAINT UK_USER_2 UNIQUE (USEREMAIL);
//
/*ALTER TABLE TELEFONO ADD CONSTRAINT PK_TELEFONO PRIMARY KEY (ID);*/

/*CREACIÓN DE CLAVES AJENAS*/
ALTER TABLE PHONE ADD CONSTRAINT FK_PHONE_USER FOREIGN KEY (USERUUID) REFERENCES USER (USERUUID);
//